name: Run Tests
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                  yarn
            - name: Build Packages
              run: |
                  yarn build
            - name: Run Tests
              run: |
                  yarn test:mock-backend:ci && yarn test
